KinoCMS/urls.py
from django.urls import path
from .views import Movie, MoviesDetailViews, ActiveMovies, MoviesViews, CinemaViews, NewsDetail

urlpatterns = [
    path('', MoviesViews.as_view(), name='movies'),
    path('<slug:slug>/', MoviesDetailViews.as_view(), name='movie'),
    path('placard', ActiveMovies.as_view(), name='placard'),
    path('cinema', CinemaViews.as_view(), name='cinema'),
    path('#', NewsDetail.as_view(), name='news'),
]

KinoCMS_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('KinoCMS.urls')),
    path('registration/', include('MainAPP.urls')),
    path('film/', include('KinoCMS.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KinoCMS/models.py
from django.db import models
from django.urls import reverse
from datetime import date


class Category(models.Model):
    name = models.CharField(max_length=160)
    description = models.TextField()
    url = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Movie(models.Model):
    title = models.CharField('Название фильма', max_length=160)
    description = models.TextField('описание')
    short_description = models.TextField('Краткое описание', blank=True, null=True, default=None)
    poster = models.ImageField('Постер', upload_to='movies/')
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=100, unique=True)
    is_active = models.BooleanField(default=False)
    price_per_film = models.PositiveIntegerField(default=0, help_text='указываем цену')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('movie', kwargs={'slug': self.url})

    class Meta:
        verbose_name = 'Фильм'
        verbose_name_plural = 'Фильмы'


class MoviShots(models.Model):
    title = models.CharField(max_length=160)
    description = models.TextField()
    image = models.ImageField(upload_to='movies_shots/')
    movie = models.ForeignKey(Movie, verbose_name='Фильмы', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Кадры из фильма'
        verbose_name_plural = 'Кадры из фильмов'


class RatingStar(models.Model):
    value = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return self.value

    class Meta:
        verbose_name = 'Звезда рейтинга'
        verbose_name_plural = 'Звезды рейтинга'


class Rating(models.Model):
    ip = models.CharField(max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name='звезда')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name='фильм')

    def __str__(self):
        return f'{self.star} - {self.movie}'

    class Meta:
        verbose_name = 'Рейтинг'
        verbose_name_plural = 'Рейтинги'


class Reviews(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=100)
    text = models.TextField(max_length=5000)
    parent = models.ForeignKey('self', verbose_name='Родитель', on_delete=models.SET_NULL, blank=True, null=True)
    movie = models.ForeignKey(Movie, verbose_name='фильм', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} - {self.movie}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'


class Cinema(models.Model):
    customer_name = models.CharField(max_length=64, blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True, default=None)
    address = models.TextField(blank=True, null=True, default=None)
    contact_phone = models.CharField(max_length=48, blank=True, null=True, default=None)

    def __str__(self):
        return self.customer_name

    class Meta:
        verbose_name = 'Кинотеатр'
        verbose_name_plural = 'Кинотеатры'


class News(models.Model):
    name = models.CharField(max_length=100)
    text = models.TextField(max_length=5000)
    publication = models.PositiveIntegerField(default=2020, help_text='Публикация')
    date_info = models.DateField('Акция стартует', default=date.today)
    cinema = models.ForeignKey(Cinema, verbose_name='Кинотеатр', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name


    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

templates/movie/active_movies.html
{% extends 'movie/movies.html' %}
{% load static %}

{% block activemovies %}
    {% csrf_token %}

    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% for place in placard_list %}
                    <div class="col-md-5" align="center">
                        <div class="card mb-1 shadow-sm">
                            <img src="{{ place.poster.url }}" class="img-fluid" align="center">
                            <text x="50%" y="50%" fill="#eceeef"
                                  dy=".3em"> {{ place.title }}</text>

                            <div class="card-body">
                                <p class="card-text"> {{ place.description|truncatechars_html:250 }} </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="{{ place.get_absolute_url }}"
                                           class="btn btn-sm btn-outline-secondary">
                                            Бронировать </a>
                                        <button type="button"
                                                class="btn btn-sm btn-outline-secondary"> {{ place.price_per_film }}
                                            UAH
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock activemovies %}

templates/movie/movi_git.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <!-- //Meta tag Keywords -->
    <title>Clack Website Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- //Meta tag Keywords -->
    <!-- Custom-Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Bootstrap-Core-CSS -->
    <!--/ Style-CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
    <!--// Style-CSS -->
    <!-- font-awesome-icons -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <!-- //font-awesome-icons -->
  <!-- /Fonts -->
    <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900" rel="stylesheet">
    <!-- //Fonts -->
</head>

<body>

    <div id="page" class="page"><!-- mian-content -->
        <div class="main-banner bg bg1" id="home" style="background-color: rgba(0, 0, 0, 0); margin-top: 0px; background-image: url(&quot;bundles/single-post-pic.jpg&quot;);">
            <!-- header -->
            <header class="header">
                <div class="container-fluid px-lg-5">
                    <!-- nav -->
                    <nav class="py-4">
                        <div id="logo">
                            <h1> <a href="index.html" class="editContent" style="outline: none; outline-offset: -2px; cursor: inherit; color: rgb(255, 255, 255); font-size: 40px; background-color: rgba(0, 0, 0, 0); font-family: &quot;Source Sans Pro&quot;, sans-serif;">DjangoMovie</a></h1>
                        </div>

                        <label for="drop" class="toggle">Menu</label>
                        <input type="checkbox" id="drop">
                        <ul class="menu mt-2">
                            <li class="active"><a href="index.html">Главная</a></li>
                            <li>
                                <!-- First Tier Drop Down -->
                                <label for="drop-2" class="toggle">Категории <span class="fa fa-angle-down" aria-hidden="true" ></span> </label>
                                <a href="#">Категории <span class="fa fa-angle-down" aria-hidden="true"></span></a>
                                <input type="checkbox" id="drop-2">
                                <ul>
                                    <li><a href="moviesingle.html">Фильмы</a></li>
                                    <li><a href="moviesingle.html">Сериалы</a></li>
                                    <li><a href="moviesingle.html">Мультфильмы</a></li>
                                </ul>
                            </li>
                            <li><a href="contact.html" style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">Вход</a></li>
                        </ul>
                    </nav>
                    <!-- //nav -->
                </div>
            </header>
            <!-- //header -->
            <!--/banner-->
            <div class="banner-info">
                <p class="editContent" >лучший сайт на django 3</p>
                <h3 class="mb-4 editContent">Все о кино</h3>
                <div class="ban-buttons">


                </div>
            </div>
            <!--// banner-inner -->

        </div>
        <!--//main-content-->
        <!---->
        <ol class="breadcrumb editContent">
            <li class="breadcrumb-item">
                <a href="index.html" class="editContent">Home</a>
            </li>
            <li class="breadcrumb-item active editContent">Single Page</li>
        </ol>
        <!---->
        <!-- banner -->
                    <!-- //product left -->
                    <!-- product right -->
                            <div class="left-ads-display col-lg-9">
                            <div class="row">
                                <div class="col-md-4 product-men">
                                    <div class="product-shoe-info editContent text-center mt-lg-4" >
                                        <div class="men-thumb-item">
                                            <img src="bundles/images/s1.jpg" class="img-fluid" alt="" >
                                        </div>
                                        <div class="item-info-product">
                                            <h4 class="">
                                                <a href="moviesingle.html" class="editContent" >К звездам</a>
                                            </h4>

                                            <div class="product_price">
                                                <div class="grid-price">
                                                    <span class="money editContent" >«The Game Begins»</span>
                                            </div>
                                        </div>
                                        <ul class="stars">
                                            <li><a href="#"><span class="fa fa-star" aria-hidden="true" ></span></a></li>
                                            <li><a href="#"><span class="fa fa-star" aria-hidden="true" ></span></a></li>
                                            <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true" ></span></a></li>
                                            <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true" ></span></a></li>
                                            <li><a href="#"><span class="fa fa-star-o" aria-hidden="true" ></span></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                        <!--<div class="grid-img-right mt-4 text-right bg bg1" >
                            <span class="money editContent" >Flat 50% Off</span>
                            <a href="moviesingle.html" class="btn" >Now</a>
                        </div>-->
                    </div>
                </div>
            </div>
        </section>
        <!-- //contact -->
        <!-- footer -->
        <footer class="editContent">
            <div class="container">
                <div class="row footer-top">
                    <div class="col-lg-4 footer-grid_section_w3layouts">
                        <h2 class="logo-2 mb-lg-4 mb-3">
                            <a href="index.html" class="editContent">
                                <span class="fa" aria-hidden="true" >
                                    Django School
                                </span>
                            </a>
                        </h2>
                        <p class="editContent" >
                            Канал для программистов и людей, которые хотят развиваться в сфере IT.
                            Видео уроки по python 3, Django 2, Django 3, JavaScript, Vue.js, HTML, CSS
                            и многое другое.
                        </p>
                        <h4 class="sub-con-fo ad-info my-4 editContent" >Catch on Social</h4>
                        <ul class="w3layouts_social_list media-soc list-unstyled">
                            <li>
                                <a href="#" class="w3pvt_facebook editContent" >
                                    <span class="fa fa-facebook-f" ></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_twitter editContent" >
                                    <span class="fa fa-twitter" ></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_dribble editContent" >
                                    <span class="fa fa-dribbble" ></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_google editContent" >
                                    <span class="fa fa-google-plus" ></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-8 footer-right">
                        <div class="w3layouts-news-letter">
                            <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3" >Newsletter</h3>

                            <p class="editContent" >By subscribing to our mailing list you will always get latest news and updates from us.</p>
                            <form action="#" method="post" class="w3layouts-newsletter">
                                <input type="email" name="Email" class="editContent" placeholder="Enter your email..." required="" >
                                <button class="btn1 btn" ><span class="fa fa-paper-plane-o" aria-hidden="true" ></span></button>

                            </form>
                        </div>
                        <div class="row mt-lg-4 bottom-w3layouts-sec-nav mx-0">
                            <div class="col-md-4 footer-grid_section_w3layouts">
                                <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3" >Разделы</h3>
                                <ul class="list-unstyled w3layouts-icons">
                                    <li>
                                        <a href="index.html" class="editContent" >Главная</a>
                                    </li>
                                    <li>
                                        <a href="about.html" class="editContent" >Категории</a>
                                    </li>
                                    <li>
                                        <a href="contact.html" class="editContent" >Контакты</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md-4 footer-grid_section_w3layouts">
                                <!-- social icons -->
                                <div class="agileinfo_social_icons">
                                    <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3" >Pages</h3>
                                    <ul class="list-unstyled w3layouts-icons">

                                        <li>
                                            <a href="#" class="editContent" >About Us</a>
                                        </li>
                                        <li>
                                            <a href="#" class="editContent" >About Us</a>
                                        </li>
                                        <li>
                                            <a href="#" class="editContent" >About Us</a>
                                        </li>
                                        <li>
                                            <a href="#" class="editContent" >About Us</a>
                                        </li>
                                        <li>
                                            <a href="#" class="editContent" >About Us</a>
                                        </li>
                                    </ul>
                                </div>
                                <!-- social icons -->
                            </div>
                            <div class="col-md-4 footer-grid_section_w3layouts my-md-0 my-5">
                                <h3 class="footer-title text-uppercase text-wh mb-lg-4 mb-3 editContent" >Contact Info</h3>
                                <div class="contact-info">
                                    <div class="footer-address-inf my-4">
                                        <h4 class="ad-info mb-2 editContent" >Email </h4>
                                        <p class="editContent" ><a href="mailto:info@example.com">info@example.com</a></p>
                                    </div>
                                    <div class="footer-address-inf">
                                        <h4 class="ad-info mb-2 editContent" >Location</h4>
                                        <p class="editContent" >New York City</p>
                                    </div>
                                </div>
                            </div>


                        </div>

                    </div>
                </div>
            </div>
        </footer>
        <!-- //footer -->
        <div class="cpy-right py-3">
            <div class="container">
                <div class="row">
                    <p class="col-md-10 text-left">© 2019 DjangoMovie. All rights reserved | Design by
                        <a href="https://djangochannel.com"> DJANGO SCHOOL.</a>
                    </p>
                    <!-- move top icon -->
                    <a href="#home" class="move-top text-right col-md-2"><span class="fa fa-long-arrow-up" aria-hidden="true" ></span></a>
                    <!-- //move top icon -->
                </div>
            </div>
        </div></div>
</body>
</html>

templates/movie/movie_detail.html
{% extends 'movie/movies.html' %}
{% load static %}
{% block film %}
    {% csrf_token %}

    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">

                <div class="col-md-10" align="center">
                    <div class="card mb-1 shadow-sm">

                        <img src="{{ movie.poster.url }}" class="img-fluid" align="center">
                        <text x="50%" y="50%" fill="#eceeef" dy=".3em"> {{ movie.title }}</text>
                        {##}
                        {#                        <div class="img-movie-shots">#}
                        {##}
                        {#                                        ВЫвод кадров из фильма#}
                        {#                            {% for image in movie.movishots_set.all %}#}
                        {#                                <img src="{{ image.image.url }}" alt="{{ image.description }}" class="img-fluid"#}
                        {#                                     align="center">#}
                        {#                            {% endfor %}#}
                        {#                        </div>#}


                        <div class="card-body">
                            <p class="card-text"> {{ movie.description }} </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <button type="button"
                                            class="btn btn-sm btn-outline-secondary"> {{ movie.price_per_film }} UAH
                                    </button>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>


        </div>

    </div>




{% endblock film %}

templates/movie/movies.html
<!doctype html>
{% load static %}
{% csrf_token %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <title> KinoCMS </title>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css' %}">

</head>
<body>
<header>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">

        <iframe name="СквознойБаннерШапка" src="//https://www.ukr.net/" width="100%" height="100%" id="if027081"
                marginwidth="0"
                marginheight="0" frameborder="0" vspace="0" hspace="0" scrolling="no"></iframe>


    </div>


    </div>

    <div class="brand-head-cont brand-head-big" style="transform: translateX(-50%) scale(0.672);">

        <div class="head"></div>

    </div>

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal">Фильмы онлайн и не только, для всей семьи.</h5>
        <nav class="my-2 my-md-0 mr-md-3">
            {% if not request.user.is_authenticated %}
                <a class="btn btn-outline-primary" href="{% url 'login' %}">Вход</a>
                <a class="btn btn-outline-primary" href="{% url 'registration' %}">Регистрация</a>
            {% else %}
                <a class='p-2 text-dark'> Здравствуйте, {{ request.user }}</a>
                <a class="btn btn-outline-primary" href="{% url 'logout' %}">Выход</a>
            {% endif %}
        </nav>
    </div>
</header>


<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <a href="#" class="h1 align-content-center ">Горячие Новинки Кино</a>

            <p>
                <a href="{% url 'placard' %}" class="btn btn-primary my-2">Афиша</a>
                <a href="#" class="btn btn-secondary my-2">Расписание</a>
                <a href="#" class="btn btn-secondary my-2">Скоро</a>
                <a href="{% url 'cinema' %}" class="btn btn-secondary my-2">Кинотеатры</a>
                <a href="#" class="btn btn-secondary my-2">Акции</a>
            </p>
        </div>
    </section>


    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% for movie in movie_list %}
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                            <div class="body">
                                <text x="50%" y="50%" fill="#eceeef" dy=".3em"> {{ movie.title }}</text>
                            </div>
                            <div class="card-body">
                                <p class="card-text"> {{ movie.description|truncatechars_html:200 }} </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">

                                        <a href="{{ movie.get_absolute_url }}"
                                           class="btn btn-sm btn-outline-secondary">
                                            Бронировать </a>
                                        <button type="button"
                                                class="btn btn-sm btn-outline-secondary"> {{ movie.price_per_film }}
                                            UAH
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>


    {% block film %} {% endblock film %}
    {% block activemovies %} {% endblock activemovies %}
    {% block cinemas %} {% endblock cinemas %}
    {% block news %} {% endblock news %}


</main>

<footer class="text-muted">
    <div class="container">

        <div style="">

            <p>У Вас выдался тяжелый денёк? Устали после учебы или работы? Не знаете, как поднять себе настроение или
                развлечься? Начинайте <strong>смотреть фильмы </strong> на нашем портале! Интересное
                кино всегда помогает расслабиться, получить заряд бодрости и позитива до конца дня.</p>
            <p>Сегодня достаточно сложно представить нашу жизнь без кинематографа. Он охватывает практически все сферы
                деятельности человека. Ему чуть больше века, однако, это искусство постоянно совершенствуется и меняется
                в лучшую сторону.</p>
            <p><img alt="фильмы онлайн" src="#"
                    style="border-radius:10px; float:left; margin-right:10px">На сегодняшний день снимается такое
                большое количество фильмов, что почти каждый день проходят премьеры по всему миру. Однако в
                стремительном ритме современной жизни не у каждого есть возможность посещать кинотеатры для того, чтобы
                насладиться просмотром желаемой кинокартины или познакомиться с новинкой, вышедшей недавно на большие
                экраны. В данном случае прекрасной альтернативой является КиноКрад. Сегодня у нас можно смотреть лучшие
                <strong>фильмы в хорошем качестве</strong>, не выходя из дома или офиса, и все это удовольствие доступно
                без регистрации. Кинотека насчитывает огромное количество онлайн фильмов всевозможных жанров, как <a
                        href="#">российского</a>, так и <a
                        href="#">зарубежного</a> производства.</p>
            <p>Представленные у нас картины заставят грустить или радоваться, заглянуть в будущее или вспомнить прошлое,
                погрузят Вас в мир <a href="#">фантастики</a> и леденящих дух ужасов, а
                так же помогут узнать много нового и интересного.</p>
            <p>Хорошей идеей будет провести свободный вечер с любимым человеком за просмотром романтической драмы.
                Собрать всех родственников можно на просмотр интересных семейных художественных <a
                        href="#">фильмов 2020</a>. Мужчинам отлично подойдут детективы и триллеры. От
                души повеселиться можно во время сеанса смешной <a href="#">комедии</a>.
                Вместе с детьми можно посмотреть кино онлайн приключенческого жанра.</p>
        </div>
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>


    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>